<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Dashboard · Hapsay</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
    <header class="border-b border-slate-200 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8"><a href="{{ route('dashboard') }}" class="text-2xl font-bold tracking-tight text-blue-700">Hapsay.</a><div class="flex items-center gap-5"><span class="hidden text-sm text-slate-500 sm:inline">{{ auth()->user()->name }}</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="text-sm font-semibold text-slate-600 hover:text-blue-700">Log out</button></form></div></div></header>
    <main class="mx-auto max-w-7xl px-6 py-10 lg:px-8">
        <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Overview</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Good day, {{ strtok(auth()->user()->name, ' ') }}.</h1><p class="mt-2 text-slate-500">Here is what needs your attention.</p></div><a href="{{ route('tasks.index') }}" class="inline-flex items-center justify-center rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white transition hover:bg-blue-800">Manage tasks</a></div>
        <section class="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p class="text-sm text-slate-500">All tasks</p><p class="mt-3 text-3xl font-semibold">{{ $totalTasks }}</p></div>
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p class="text-sm text-slate-500">Pending</p><p class="mt-3 text-3xl font-semibold text-amber-600">{{ $pendingTasks }}</p></div>
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p class="text-sm text-slate-500">Completed</p><p class="mt-3 text-3xl font-semibold text-emerald-600">{{ $completedTasks }}</p></div>
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p class="text-sm text-slate-500">Upcoming</p><p class="mt-3 text-3xl font-semibold text-blue-700">{{ $upcomingTasks->count() }}</p></div>
        </section>
        <section class="mt-10 grid gap-8 lg:grid-cols-5">
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 lg:col-span-3"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">Recent tasks</h2><a href="{{ route('tasks.index') }}" class="text-sm font-semibold text-blue-700 hover:text-blue-800">View all</a></div><div class="mt-5 divide-y divide-slate-100">@forelse ($tasks->take(5) as $task)<div class="flex items-start gap-4 py-4"><span class="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full {{ $task->status === 'completed' ? 'bg-emerald-500' : ($task->priority === 'high' ? 'bg-rose-500' : 'bg-blue-500') }}"></span><div class="min-w-0 flex-1"><p class="font-medium {{ $task->status === 'completed' ? 'text-slate-400 line-through' : '' }}">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-500">{{ str_replace('_', ' ', $task->status) }} · {{ ucfirst($task->priority) }} priority</p></div>@if ($task->due_date)<time class="whitespace-nowrap text-sm text-slate-500">{{ $task->due_date->format('M j') }}</time>@endif</div>@empty<div class="py-12 text-center"><p class="font-medium">No tasks yet</p><p class="mt-1 text-sm text-slate-500">Create your first task to get started.</p><a href="{{ route('tasks.index') }}" class="mt-4 inline-block text-sm font-semibold text-blue-700">Create a task</a></div>@endforelse</div></div>
            <div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 lg:col-span-2"><h2 class="text-lg font-semibold">Coming up</h2><div class="mt-5 space-y-4">@forelse ($upcomingTasks->take(5) as $task)<div class="rounded-xl bg-slate-50 p-4"><p class="font-medium">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-500">Due {{ $task->due_date->format('l, M j') }}</p></div>@empty<p class="py-8 text-center text-sm text-slate-500">Nothing due soon. Nice work.</p>@endforelse</div></div>
        </section>
    </main>
</body>
</html>
